### ISSUE TITLE
基于fish redux使用时报错  初始化问题

### ISSUE THREAD

**Issue by niugengyun** [peng8350/flutter_pulltorefresh#122]
```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: Try not to call requestRefresh() before build,please call after the ui was rendered
flutter: 'package:pull_to_refresh/src/smart_refresher.dart': Failed assertion: line 259 pos 12: 'position !=
flutter: null'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RefreshController.requestRefresh (package:pull_to_refresh/src/smart_refresher.dart:259:12)
flutter: #3      new RefreshController.<anonymous closure> (package:pull_to_refresh/src/smart_refresher.dart:251:9)
flutter: #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:960:9)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #10     _invoke (dart:ui/hooks.dart:219:10)
flutter: #11     _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by peng8350** [comment]
更新1.4.8试试还有没有这个问题

**Comment by niugengyun** [comment]
> 更新1.4.8试试还有没有这个问题

我自己解决了，但是点击tab切换时 
```
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching notifications for ValueNotifier<RefreshStatus>:
flutter: setState() or markNeedsBuild() called during build.
flutter: This WaterDropHeader widget cannot be marked as needing to build because the framework is already in
flutter: the process of building widgets. A widget can be marked as needing to be built during the build
flutter: phase only if one of its ancestors is currently building. This exception is allowed because the
flutter: framework builds parent widgets before children, which means a dirty descendant will always be
flutter: built. Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   WaterDropHeader(dependencies: [RefreshConfiguration, _ScrollableScope], state:
flutter:   _WaterDropHeaderState#12f95(tickers: tracking 2 tickers))
flutter: The widget which was currently being built when the offending call was made was:
flutter:   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#ea1e3](state:
flutter:   RawGestureDetectorState#32ff5(gestures: <none>, behavior: opaque))
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3503:11)
flutter: #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3529:6)
flutter: #2      State.setState (package:flutter/src/widgets/framework.dart:1133:14)
flutter: #3      _RefreshIndicatorState&State&IndicatorStateMixin.update (package:pull_to_refresh/src/internals/indicator_wrap.dart:380:18)
flutter: #4      RefreshIndicatorState._handleModeChange (package:pull_to_refresh/src/internals/indicator_wrap.dart:141:5)
flutter: #5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
flutter: #6      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:270:5)
flutter: #7      _RefreshIndicatorState&State&IndicatorStateMixin.initState (package:pull_to_refresh/src/internals/indicator_wrap.dart:428:59)
flutter: #8      _WaterDropHeaderState.initState (package:pull_to_refresh/src/indicator/waterdrop_header.dart:88:11)
flutter: #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #12     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
flutter: #13     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
flutter: #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
flutter: #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #69     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
flutter: #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #89     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
flutter: #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #95     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
flutter: #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #99     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1034:36)
flutter: #100    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1019:20)
flutter: #101    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
flutter: #102    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1012:11)
flutter: #103    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:275:23)
flutter: #104    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
flutter: #105    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
flutter: #106    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
flutter: #107    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:264:5)
flutter: #108    RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:410:5)
flutter: #109    RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:209:17)
flutter: #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #111    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
flutter: #112    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
flutter: #113    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
flutter: #114    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
flutter: #115    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
flutter: #116    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
flutter: #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #119    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #120    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #121    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #125    _invoke (dart:ui/hooks.dart:219:10)
flutter: #126    _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: The ValueNotifier<RefreshStatus> sending notification was:
flutter:   ValueNotifier<RefreshStatus>#3b6ce(RefreshStatus.idle)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by peng8350** [comment]
能不能给个样例代码

**Comment by niugengyun** [comment]
```dart
import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart'
    hide RefreshIndicator, RefreshIndicatorState;
import 'package:flutter/widgets.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:shenghuopai/utils/helper.dart';

import 'action.dart';
import 'state.dart';

Widget buildView(OrderState state, Dispatch dispatch, ViewService viewService) {
  final ListAdapter listAdapter = viewService.buildAdapter();

  // 顶部按钮
  final Map<int, Widget> btns = <int, Widget>{
    1: Padding(
      padding: EdgeInsets.only(left: setWidth(5), right: setWidth(5)),
      child: Text(
        "自己出单",
        style: TextStyle(
            fontSize: setSp(13),
            color: state.currentValue == 1 ? Colors.white : Colors.black),
      ),
    ),
    2: Padding(
      padding: EdgeInsets.only(left: setWidth(5), right: setWidth(5)),
      child: Text(
        "粉丝出单",
        style: TextStyle(
            fontSize: setSp(13),
            color: state.currentValue == 2 ? Colors.white : Colors.black),
      ),
    ),
  };

  // tabs
  List<Widget> tabs = <Widget>[
    Tab(text: "全部"),
    Tab(text: "有效"),
    Tab(text: "失效"),
  ];

  return DefaultTabController(
    length: tabs.length,
    child: Scaffold(
      floatingActionButton: Builder(builder: (BuildContext context) {
        return FloatingActionButton(
          child: Icon(Icons.arrow_upward),
          foregroundColor: Colors.white,
          backgroundColor: Colors.black,
          elevation: 7.0,
          highlightElevation: 14.0,
          onPressed: () {
            state.scrollController.animateTo(.0,
                duration: Duration(milliseconds: 200), curve: Curves.ease);
          },
          mini: true,
          shape: CircleBorder(),
        );
      }),
      floatingActionButtonLocation: FloatingActionButtonLocation.endFloat,
      appBar: AppBar(
        elevation: 1,
        title: CupertinoSegmentedControl(
          onValueChanged: (value) =>
              dispatch(OrderActionCreator.onChangeValueAction(value)),
          groupValue: state.currentValue,
          selectedColor: Color.fromRGBO(36, 36, 36, 1),
          borderColor: Color.fromRGBO(36, 36, 36, 1),
          pressedColor: Colors.white,
          children: btns,
        ),
        actions: <Widget>[
          FlatButton(
            onPressed: () => jump(viewService.context, "hongtang://bind_order"),
            child: Text("找回订单"),
          ),
        ],
        bottom: TabBar(
          isScrollable: true,
          indicatorSize: TabBarIndicatorSize.label,
          tabs: tabs,
        ),
      ),
      body: Container(
        color: Color.fromRGBO(240, 240, 240, 1),
        child: TabBarView(
          children: tabs.map((_) {
            return SmartRefresher(
              enablePullDown: true,
              enablePullUp: true,
              header: WaterDropHeader(),
              controller: state.refreshController,
              onRefresh: () => dispatch(OrderActionCreator.onRefreshAction()),
              onLoading: () => dispatch(OrderActionCreator.onLoadMoreAction()),
              child: ListView.builder(
                controller: state.scrollController,
                itemBuilder: listAdapter.itemBuilder,
                itemCount: listAdapter.itemCount,
              ),
            );
          }).toList(),
        ),
      ),
    ),
  );
}

```

**Comment by niugengyun** [comment]
> 能不能给个样例代码

发个微信我加你

**Comment by peng8350** [comment]
它的错误指向我内部的setState,感觉跟TabBarView的机制有关。不过你上面的代码,我有点疑惑的是,为什么要共用ScrollController和RefreshController

**Comment by peng8350** [comment]
然后我demo也是用TabBarView,没有这问题

**Comment by niugengyun** [comment]
> ScrollController

ScrollController  用户返回顶部    ，RefreshController没用到啊

**Comment by niugengyun** [comment]
> 然后我demo也是用TabBarView,没有这问题

能否给个tabbar的例子

**Comment by peng8350** [comment]
readme里基础用法就是tabbar,我那边四个页面对应4个controller,

**Comment by niugengyun** [comment]
> readme里基础用法就是tabbar,我那边四个页面对应4个controller,

我看了 咱俩的代码基本一样的。
我的这个问题怎么解决呢

**Comment by peng8350** [comment]
不一样,你的只是一个controller,你tabbarview不是有三个页面嘛，也就是三个refresher，你就得用三个refreshcontroller来对应。你给出的代码就是三个refresher对应一个controller.

**Comment by niugengyun** [comment]
> 不一样,你的只是一个controller,你tabbarview不是有三个页面嘛，也就是三个refresher，你就得用三个refreshcontroller来对应。你给出的代码就是三个refresher对应一个controller.

感谢指正，按照您说的做，已经好了，不是fish redux的问题。是我自己的问题

**Comment by parcool** [comment]
切换tab会重新构建页面。比如2个tab页面对应2个SmartRefresher，切换后又重新刷新了(initialRefresh: true)，如果initialRefresh: false的话，2个页面是空数据。你的示例里是数据是定死在顶部的，所以看不出来。如果把2个页面滑动一点距离的话就能看出来了。这个问题怎么解决？

**Comment by parcool** [comment]
我的错。添加with AutomaticKeepAliveClientMixin即可，跟本库没关系

**Comment by Maclaon** [comment]
> > 不一样,你的只是一个controller,你tabbarview不是有三个页面嘛，也就是三个refresher，你就得用三个refreshcontroller来对应。你给出的代码就是三个refresher对应一个controller.
> 
> 感谢指正，按照您说的做，已经好了，不是fish redux的问题。是我自己的问题

能否给个代码示例，遇到Fish_redux和pull_to_refresh，上拉加载只能加载一次，后续就不触发加载了，非常奇怪！
