### ISSUE TITLE
Error when setting both enablePullUp and enablePullDown to false

### ISSUE THREAD

**Issue by magicleon94** [peng8350/flutter_pulltorefresh#148]
When I set both  `enablePullUp` and `enablePullDown` to `false`, `RefreshController` instance has its `position` property `null`.

This results in a crash and inability to scroll the child. Here's the stack trace:
```
I/flutter ( 4862): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4862): The following NoSuchMethodError was thrown during performLayout():
I/flutter ( 4862): The getter 'context' was called on null.
I/flutter ( 4862): Receiver: null
I/flutter ( 4862): Tried calling: context
I/flutter ( 4862): 
I/flutter ( 4862): When the exception was thrown, this was the stack:
I/flutter ( 4862): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 4862): #1      RefreshPhysics.createBallisticSimulation (package:pull_to_refresh/src/internals/refresh_physics.dart:250:42)
I/flutter ( 4862): #2      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:146:43)
I/flutter ( 4862): #3      IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:149:14)
I/flutter ( 4862): #4      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:490:14)
I/flutter ( 4862): #5      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:106:11)
I/flutter ( 4862): #6      ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:461:7)
I/flutter ( 4862): #7      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1256:20)
I/flutter ( 4862): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4862): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4862): #28     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 4862): #29     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 4862): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 4862): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 4862): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 4862): #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 4862): #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 4862): #35     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 4862): #39     _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 4862): #40     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 4862): (elided 3 frames from package dart:async)
```

Error was encountered with this configuration:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.36.1)
[✓] Proxy Configuration
```

**Comment by peng8350** [comment]
you can remove SmartRefresher from ListView if you don't need to pull-down-refresh or pull-up-load
