### ISSUE TITLE
child view can not be Container

### ISSUE THREAD

**Issue by jinfagang** [peng8350/flutter_pulltorefresh#3]
The child parameter can not be Container:
```
return new SmartRefresher(
        enablePullDown: true,
        enablePullUp: true,
        // refreshMode: this.refreshing,
        // loadMode: this.loading,
        onRefresh: _onRefresh,
        // headerBuilder: _buildHeader,
        // onOffsetChange: _onOffsetCallback,
        child: new Container(
            color: Colors.white,
            child: new Column(
              children: <Widget>[
                // headBannerSection,
                carouselBanner,
                _buildCategorySection(context),
                _buildListViewContent(),
              ],
            )));
  }
```
This gives an error.

**Comment by peng8350** [comment]
Yes,I have modified the latest version to be ScrollView type only, because listView can not cache item without doing so. You can wrap it in ListView too

**Comment by jinfagang** [comment]
@peng8350 Thanks for your reply, I am previously using a ListView contains all my sections, however there was an error:
```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The method 'onDragEnd' was called on null.
Receiver: null
Tried calling: onDragEnd(Instance of 'ScrollEndNotification')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      _SmartRefresherState._handleScrollEnd (package:pull_to_refresh/src/smart_refresher.dart:117:41)
#2      _SmartRefresherState._dispatchScrollEvent (package:pull_to_refresh/src/smart_refresher.dart:137:7)
#3      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:125:27)
#4      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
#5      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:35:18)
#6      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3295:39)
#7      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:59:12)
```

Here is my codes:

```
@override
  Widget build(BuildContext context) {
    return new SmartRefresher(
        enablePullDown: true,
        enablePullUp: true,
        // refreshMode: this.refreshing,
        // loadMode: this.loading,
        controller: _refreshController,
        onRefresh: _onRefresh,
        // headerBuilder: _buildHeader,
        // onOffsetChange: _onOffsetCallback,
        // child: new Container(
        //     color: Colors.white,
        //     child: new Column(
        //       children: <Widget>[
        //         // headBannerSection,
        //         carouselBanner,
        //         _buildCategorySection(context),
        //         _buildListViewContent(),
        //       ],
        //     )));
        child: new ListView(
          children: <Widget>[
            carouselBanner,
                _buildCategorySection(context),
                _buildListViewContent(),
          ],
        )
      );
  }
```

The comment are the previous code, any suggestions?

**Comment by peng8350** [comment]
The problem is that there are no default headerBuilder and footerBuilder inside, you only need to add the two attributes. I'll give it a default indicator in the next version

**Comment by jinfagang** [comment]
Thanks!!! Solved problem!!
