### ISSUE TITLE
flutter 更新后报错

### ISSUE THREAD

**Issue by keluokeda** [peng8350/flutter_pulltorefresh#307]
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15:
'scrollOffsetCorrection != 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  SmartRefresher
  file:///Users/yuyanhui/Desktop/flutter_project/flutter_provider_zhihu/lib/page/base_json_list_page.dart:12:12

When the exception was thrown, this was the stack:
#2      new SliverGeometry (package:flutter/src/rendering/sliver.dart:556:15)
#3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:180:20)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#5      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
#6      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
#7      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
#8      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
#9      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
#10     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1115:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1054:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:970:5)
#19     _invoke (dart:ui/hooks.dart:253:10)
#20     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)

The following RenderObject was being processed when the exception was fired: RenderSliverList#0ae8e relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: SliverList ← Viewport ← IgnorePointer-[GlobalKey#17b55] ← Semantics ← _PointerListener ←
    Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#9add6] ← _PointerListener ← Listener
    ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#a095a] ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward,
    scrollOffset: 245.0, remainingPaintExtent: 712.0, crossAxisExtent: 375.0, crossAxisDirection:
    AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 1207.0, cacheOrigin:
    -245.0)
  geometry: SliverGeometry(scrollExtent: 6123.6, paintExtent: 712.0, maxPaintExtent: 6123.6,
    hasVisualOverflow: true, cacheExtent: 1212.0)
  currently live children: 0 to 5
This RenderObject had the following descendants (showing up to depth 5):
    child with index 0: RenderIndexedSemantics#fc867 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderRepaintBoundary#8126d relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderLimitedBox#98a63 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderConstrainedBox#86a55 NEEDS-PAINT
    child with index 1: RenderIndexedSemantics#e27d3 relayoutBoundary=up2 NEEDS-PAINT
      child: RenderRepaintBoundary#dab0a relayoutBoundary=up3 NEEDS-PAINT
        child: RenderFlex#5ae77 relayoutBoundary=up4 NEEDS-PAINT
          child 1: RenderFlex#14122 relayoutBoundary=up5 NEEDS-PAINT
            child 1: RenderConstrainedBox#50d80 relayoutBoundary=up6 NEEDS-PAINT
            child 2: RenderConstrainedBox#b613f relayoutBoundary=up6 NEEDS-PAINT
            child 3: RenderConstrainedBox#5ed07 relayoutBoundary=up6 NEEDS-PAINT
          child 2: RenderPadding#a6394 relayoutBoundary=up5 NEEDS-PAINT
            child: RenderFlex#49530 relayoutBoundary=up6 NEEDS-PAINT
          child 3: RenderFlex#d2a05 relayoutBoundary=up5 NEEDS-PAINT
            child 1: RenderPadding#5955b relayoutBoundary=up6 NEEDS-PAINT
            child 2: RenderFlex#e85e2 relayoutBoundary=up6 NEEDS-PAINT
          child 4: RenderConstrainedBox#2a33b relayoutBoundary=up5 NEEDS-PAINT
            child: RenderPositionedBox#c96c7 relayoutBoundary=up6 NEEDS-PAINT
    child with index 2: RenderIndexedSemantics#52e95 relayoutBoundary=up2 NEEDS-PAINT
      child: RenderRepaintBoundary#b89a2 relayoutBoundary=up3 NEEDS-PAINT
        child: RenderFlex#40352 relayoutBoundary=up4 NEEDS-PAINT
          child 1: RenderLimitedBox#3a2e4 relayoutBoundary=up5 NEEDS-PAINT
            child: RenderConstrainedBox#9357d relayoutBoundary=up6 NEEDS-PAINT
          child 2: RenderPadding#12ca7 relayoutBoundary=up5 NEEDS-PAINT
            child: RenderFlex#89f38 relayoutBoundary=up6 NEEDS-PAINT
          child 3: RenderLimitedBox#96199 relayoutBoundary=up5 NEEDS-PAINT
            child: RenderConstrainedBox#28f6d relayoutBoundary=up6 NEEDS-PAINT
          child 4: RenderConstrainedBox#87c63 relayoutBoundary=up5 NEEDS-PAINT
            child: RenderPositionedBox#01efa relayoutBoundary=up6 NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: NoSuchMethodError: The method '-' was called on null.

```

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.77, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
    • Flutter version 1.20.0-3.0.pre.77 at /Users/yuyanhui/Desktop/flutter/flutter
    • Framework revision 06d0cd514e (9 hours ago), 2020-06-26 15:34:41 -0700
    • Engine revision fc0e27210c
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 63cf56d925)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yuyanhui/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7846.93

 
[✓] Connected device (4 available)            
    • VCE AL00      • 46F4C19227010639                     • android-arm64  •
      Android 10 (API 29)
    • iPhone 11 Pro • 6AFEC444-7EA8-4C96-A204-820B3B16F3AE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server    • web-server                           • web-javascript •
      Flutter Tools
    • Chrome        • chrome                               • web-javascript • Google
      Chrome 83.0.4103.116

• No issues found!

```

**Comment by peng8350** [comment]
I saw it,they make a breaking changes in sliver_list.dart.

**Comment by peng8350** [comment]
问题没法重现,起码给个样例代码把？

**Comment by keluokeda** [comment]
我不知道这个应不应该算是一个bug，如果child里面包含空的Container，滑动的时候先往下滑动，在往上滑动就会报错，什么都不显示
```
import 'package:flutter/material.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final RefreshController _refreshController = RefreshController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('滑动报错'),
      ),
      body: SmartRefresher(
        controller: _refreshController,
        child: ListView.builder(
          itemBuilder: (context, index) {
            if (index == 0) {
              return Container();
            } else if (index == 101) {
              return Container();
            } else {
              return ListTile(
                title: Text(index.toString()),
              );
            }
          },
          itemCount: 102,
        ),
      ),
    );
  }
}
```
你可以试试

**Comment by peng8350** [comment]
你的这个例子我试了，还是没法重现,版本为1.17.5(最新)。更新flutter版本试试,或者检查下有没有变动flutter内部的代码,比如RenderSliverList,RenderViewport,因为错误定位在渲染层上

**Comment by keluokeda** [comment]
我这边还是不行，我的flutter doctor
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.117, on Mac OS X 10.15.5 19F101,
    locale zh-Hans-CN)
    • Flutter version 1.20.0-3.0.pre.117 at
      /Users/yuyanhui/Desktop/flutter/flutter
    • Framework revision 3f4f91532f (8 hours ago), 2020-07-01 13:58:01 -0400
    • Engine revision 88a8e9db18
    • Dart version 2.9.0 (build 2.9.0-19.0.dev bec128612c)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yuyanhui/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7846.93

[✓] Connected device (4 available)
    • VCE AL00 (mobile)      • 46F4C19227010639                     •
      android-arm64  • Android 10 (API 29)
    • iPhone 11 Pro (mobile) • 6AFEC444-7EA8-4C96-A204-820B3B16F3AE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```


![屏幕录制2020-07-02 上午9 42 50 2020-07-02 09_50_43](https://user-images.githubusercontent.com/16809185/86307534-8fd5a800-bc49-11ea-9587-165a0b776d00.gif)

**Comment by peng8350** [comment]
经过在1.20实测,这问题即便不用我的库也会产生这个异常,你应该向flutter反馈。

**Comment by peng8350** [comment]
例子
```dart
import 'package:flutter/material.dart';


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final RefreshController _refreshController = RefreshController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('滑动报错'),
      ),
      body: ListView.builder(
        physics: BouncingScrollPhysics(),
        itemBuilder: (context, index) {
          if (index == 0) {
            return Container();
          } else if (index == 101) {
            return Container();
          } else {
            return ListTile(
              title: Text(index.toString()),
            );
          }
        },
        itemCount: 102,
      ),
    );
  }
}
```
