### ISSUE TITLE
Not working in iOS14

### ISSUE THREAD

**Issue by nagarwa2** [peng8350/flutter_pulltorefresh#352]
Unable to use the widget with iOS 14. Getting below error

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12: '_pendingDimensions': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  SmartRefresher file:///XXX/XXX/XXX/XXX/XXX/lib/Components/PostWidget.dart:82:15
When the exception was thrown, this was the stack: 
#2      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:582:12)
#3      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:108:11)
#4      RenderSliverRefresh.performLayout (package:pull_to_refresh/src/internals/slivers.dart:189:39)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#6      RenderSliverRefresh.layout (package:pull_to_refresh/src/internals/slivers.dart:152:13)
...
The following RenderObject was being processed when the exception was fired: RenderSliverRefresh#84a9d relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 757.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 757.0, remainingCacheExtent: 1007.0, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
...    scrollExtent: 0.0
...    hidden
...    maxPaintExtent: 0.0
RenderObject: RenderSliverRefresh#84a9d relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 757.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 757.0, remainingCacheExtent: 1007.0, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
    scrollExtent: 0.0
    hidden
    maxPaintExtent: 0.0
...  child: RenderRotatedBox#ef04b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...    size: Size(414.0, 60.0)
...    child: RenderConstrainedBox#d6e1b relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 60.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=60.0)
...      child: RenderPositionedBox#73e01 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=60.0)
...        size: Size(414.0, 60.0)
...        alignment: center
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderWrap#ca794 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(128.0, 18.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=60.0)
...          size: Size(158.0, 24.0)
...          direction: horizontal
...          alignment: center
...          spacing: 15.0
...          runAlignment: start
...          runSpacing: 0.0
...          crossAxisAlignment: 0.0
...          textDirection: ltr
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by tigerzhang08** [comment]
I meet same issues

**Comment by Rodiii** [comment]
Hi all,
there is a dirty workaround to fix this issue:
Just revert the applyContentDimensions in scroll_position.dart to this commit, then pull_to_refresh works again...

https://github.com/flutter/flutter/commit/eef4220a878fd5dfe1551f76a78168347d6aa9eb#diff-d5d3b3f6ed21039a1a1e9413d814c5ee

**Comment by ghenry** [comment]
I'm seeing this on flutter beta channel on Android built on Linux. Not just related to iOS

**Comment by ghenry** [comment]
```
I/flutter (26207): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (26207): The following assertion was thrown during performLayout():
I/flutter (26207): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12:
I/flutter (26207): '_pendingDimensions': is not true.
I/flutter (26207): 
I/flutter (26207): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (26207): more information in this error message to help you determine and fix the underlying cause.
I/flutter (26207): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (26207):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (26207): 
I/flutter (26207): The relevant error-causing widget was:
I/flutter (26207):   SliverRefresh
I/flutter (26207):   file:///home/xxx/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.6.1/lib/src/internals/indicator_wrap.dart:315:12
I/flutter (26207): 
I/flutter (26207): When the exception was thrown, this was the stack:
I/flutter (26207): #2      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:582:12)
I/flutter (26207): #3      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:108:11)
I/flutter (26207): #4      RenderSliverRefresh.performLayout (package:pull_to_refresh/src/internals/slivers.dart:189:39)
I/flutter (26207): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (26207): #6      RenderSliverRefresh.layout (package:pull_to_refresh/src/internals/slivers.dart:147:13)
I/flutter (26207): #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:507:13)
I/flutter (26207): #8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1561:12)
I/flutter (26207): #9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1470:20)
I/flutter (26207): #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (26207): #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter (26207): #12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:436:19)
I/flutter (26207): #13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
I/flutter (26207): #14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (26207): #15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (26207): #19     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (26207): #20     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (26207): (elided 5 frames from class _AssertionError and dart:async)
```

flutter doctor:

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.0-12.1.pre at /home/xxx/development/flutter
    • Framework revision 8b3760638a (5 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)
```

**Comment by ghenry** [comment]
Sorry, it is working but the refresh icon just kicks in once you've pulled down a bit.

**Comment by peng8350** [comment]
Try 1.6.2,If it work,please tell me.I ａｍ going to closeit

**Comment by ghenry** [comment]
Working now. Thanks for the fast changes!

**Comment by ghenry** [comment]
I'll add, I've not testing on iOS 14, just Flutter beta on Android as the same issue was happening there. You need beta to deploy to an iOS 14 device properly at the moment:

> Upgrading to Flutter 1.22 beta allows you to build, test, and deploy to iOS without issue. Upgrading to 1.20.4 stable allows you to build and deploy to iOS 14, but not debug.

https://flutter.dev/docs/development/ios-14#launching-flutter-with-flutter-tools

so probably fixed on iOS 14. I'll be testing that later this week.
