### ISSUE TITLE
列表下拉过程中一直报错，下拉刷新后无法继续滑动

### ISSUE THREAD

**Issue by smokyfog** [peng8350/flutter_pulltorefresh#357]
您好，我是一个刚开始接触flutter的小白，刚刚使用您的插件遇到了：列表下拉过程中一直报错，下拉刷新后无法继续滑动的问题，希望能得到您的帮助

**代码如下**

```
import 'package:flutter/material.dart';

import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:flutter/cupertino.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  List<String> items = ["1", "2", "3", "4", "5", "6", "7", "8"];
  RefreshController _refreshController =
  RefreshController(initialRefresh: false);

  void _onRefresh() async {
    // monitor network fetch
    await Future.delayed(Duration(milliseconds: 1000));
    // if failed,use refreshFailed()
    _refreshController.refreshCompleted();
  }

  void _onLoading() async {
    // monitor network fetch
    await Future.delayed(Duration(milliseconds: 1000));
    // if failed,use loadFailed(),if no data return,use LoadNodata()
    items.add((items.length + 1).toString());
    if (mounted)
      setState(() {

      });
    _refreshController.loadComplete();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: SmartRefresher(
        enablePullDown: true,
        enablePullUp: true,
        header: WaterDropHeader(),
        footer: CustomFooter(
          builder: (BuildContext context, LoadStatus mode) {
            Widget body;
            if (mode == LoadStatus.idle) {
              body = Text("上拉加载");
            }
            else if (mode == LoadStatus.loading) {
              body = CupertinoActivityIndicator();
            }
            else if (mode == LoadStatus.failed) {
              body = Text("加载失败！点击重试！");
            }
            else if (mode == LoadStatus.canLoading) {
              body = Text("松手,加载更多!");
            }
            else {
              body = Text("没有更多数据了!");
            }
            return Container(
              height: 55.0,
              child: Center(child: body),
            );
          },
        ),
        controller: _refreshController,
        onRefresh: _onRefresh,
        onLoading: _onLoading,
        child: ListView.builder(
          itemBuilder: (c, i) => Card(child: Center(child: Text(items[i]))),
          itemExtent: 100.0,
          itemCount: items.length,
        ),
      ),
    );
  }
}
```

**初始化时报错如下**

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 593 pos 12: '_pendingDimensions': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  SliverRefresh file:///Users/xxx/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.6.1/lib/src/internals/indicator_wrap.dart:315:12
When the exception was thrown, this was the stack: 
#2      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:593:12)
#3      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:103:11)
#4      RenderSliverRefresh.performLayout (package:pull_to_refresh/src/internals/slivers.dart:189:39)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#6      RenderSliverRefresh.layout (package:pull_to_refresh/src/internals/slivers.dart:152:13)
...
The following RenderObject was being processed when the exception was fired: RenderSliverRefresh#0e33b relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 796.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 796.0, remainingCacheExtent: 1046.0, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
...    scrollExtent: 0.0
...    hidden
...    maxPaintExtent: 0.0
RenderObject: RenderSliverRefresh#0e33b relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 796.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 796.0, remainingCacheExtent: 1046.0, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
    scrollExtent: 0.0
    hidden
    maxPaintExtent: 0.0
...  child: RenderRotatedBox#57c34 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...    size: Size(414.0, 60.0)
...    child: RenderAnimatedOpacity#f0f8f relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 60.0)
...      opacity: AnimationController#c55d5(⏭ 1.000; paused)
...      child: RenderConstrainedBox#81eb8 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...        size: Size(414.0, 60.0)
...        additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=60.0)
...        child: RenderStack#42d5d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, h=60.0)
...          size: Size(414.0, 60.0)
...          alignment: AlignmentDirectional.topStart
...          textDirection: ltr
...          fit: loose
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**列表滑动中报错如下**

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 593 pos 12: '_pendingDimensions': is not true.
The relevant error-causing widget was: 
  WaterDropHeader file:///Users/xxx/Documents/study/flutter/flutter_pulltorefresh_test/lib/main.dart:64:17
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 593 pos 12: '_pendingDimensions': is not true.
The relevant error-causing widget was: 
  WaterDropHeader file:///Users/xxx/Documents/study/flutter/flutter_pulltorefresh_test/lib/main.dart:64:17
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 593 pos 12: '_pendingDimensions': is not true.

```

**下拉刷新后报错如下**
```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
Updated layout information required for RenderRotatedBox#23f35 relayoutBoundary=up2 NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2647 pos 12: '!_needsLayout'
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Rodiii** [comment]
Duplicate to https://github.com/peng8350/flutter_pulltorefresh/issues/352 ?
