### ISSUE TITLE
下拉刷新的时候，往上推，放开，再往下拉（概率贼大的一个异常）

### ISSUE THREAD

**Issue by niyige** [peng8350/flutter_pulltorefresh#372]
异常如下：
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 571 pos 12: '_drag == null': is not true.

'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 580 pos 12: '_drag == null': is not true.

虽然爆了上面异常，但是能正常使用。

**Comment by wz19900616** [comment]
反过来也会.  页面下拉到底部触发加载下一页的时候 ,迅速滚到顶部 ,然后就无法滑动了 .

**Comment by HannibalKcc** [comment]
我遇到同样的问题，以为是我使用姿势的问题。但是应用了 readme 给出的 demo 代码依旧有这个问题。版本 1.6.1

**Comment by sososdk** [comment]
`1.6.3` 还是有这个问题. 

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (5 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

```
┌───────────────────────────────────────────────────────────────────────────────                                 
│ 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 571 pos 12: '_drag == null': is not true.
├···············································································                                 
│ #0   _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)                                     
│ #1   _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)                                        
│ #2   ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:571:12)                      
│ #3   DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:401:51)  
│ #4   GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)                    
│ #5   DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:401:7)                       
│ #6   DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:264:7)                
│ #7   GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:103:7)                         
├···············································································                                 
│
└───────────────────────────────────────────────────────────────────────────────                                 
```
