### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe

### ISSUE THREAD

**Issue by telinx** [peng8350/flutter_pulltorefresh#378]
occured a exception when use this plugin in tab view. 
flutter version: 1.22
Version: pull_to_refresh: 1.6.2
problem:
```
I/flutter (27856): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (27856): The following assertion was thrown while dispatching notifications for ValueNotifier<RefreshStatus>:
I/flutter (27856): Looking up a deactivated widget's ancestor is unsafe.
I/flutter (27856): At this point the state of the widget's element tree is no longer stable.
I/flutter (27856): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
I/flutter (27856): calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
I/flutter (27856): 
I/flutter (27856): When the exception was thrown, this was the stack:
I/flutter (27856): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3906:9)
I/flutter (27856): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3920:6)
I/flutter (27856): #2      Element.ancestorStateOfType (package:flutter/src/widgets/framework.dart:4026:12)
I/flutter (27856): #3      SmartRefresher.ofState (package:pull_to_refresh/src/smart_refresher.dart:277:21)
I/flutter (27856): #4      RefreshIndicatorState._handleModeChange (package:pull_to_refresh/src/internals/indicator_wrap.dart:243:24)
I/flutter (27856): #5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
I/flutter (27856): #6      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:292:5)
I/flutter (27856): #7      IndicatorStateMixin.initState (package:pull_to_refresh/src/internals/indicator_wrap.dart:639:59)
I/flutter (27856): #8      _WaterDropHeaderXState.initState (package:celestyles_app/ui/widgets/waterdrop_headerx.dart:92:11)
I/flutter (27856): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
I/flutter (27856): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
I/flutter (27856): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (27856): #12     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (27856): #13     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:225:11)
I/flutter (27856): ...     Normal element mounting (82 frames)
I/flutter (27856): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (27856): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
I/flutter (27856): #97     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:140:18)
I/flutter (27856): #98     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
I/flutter (27856): #99     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:120:11)
I/flutter (27856): #100    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1883:59)
I/flutter (27856): #101    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
I/flutter (27856): #102    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1883:14)
I/flutter (27856): #103    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:229:7)
I/flutter (27856): #104    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:355:5)
I/flutter (27856): #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (27856): #106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
I/flutter (27856): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (27856): #108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
I/flutter (27856): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (27856): #110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
I/flutter (27856): #111    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (27856): #112    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
I/flutter (27856): #113    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (27856): #114    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
I/flutter (27856): #115    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (27856): #116    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
I/flutter (27856): #117    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27856): #118    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter (27856): #119    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:436:19)
I/flutter (27856): #120    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
I/flutter (27856): #121    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (27856): #122    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (27856): #123    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (27856): #124    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (27856): #128    _invoke (dart:ui/hooks.dart:251:10)
I/flutter (27856): #129    _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (27856): (elided 3 frames from dart:async)
I/flutter (27856): 
I/flutter (27856): The ValueNotifier<RefreshStatus> sending notification was:
I/flutter (27856):   ValueNotifier<RefreshStatus>#9cc7c(RefreshStatus.idle)
```

SmartRefresher.ofState (package:pull_to_refresh/src/smart_refresher.dart:277:21)
```
 276 static SmartRefresherState ofState(BuildContext context) {
 277   return context?.ancestorStateOfType(TypeMatcher<SmartRefresherState>());
 278 }
```

**Comment by Hikaru-Otaki** [comment]
me too

**Comment by peng8350** [comment]
If you only put the exception log and not give the step or reproduce code how to trigger the issue,I have no idea how to fix.the same as #316 .

**Comment by SebAubin** [comment]
We have the same error. The implementation is simple as in the example:

```sr.SmartRefresher(
            header: sr.ClassicHeader(
              idleText: '',
              refreshingText: '',
              releaseText: '',
            ),
            controller: _refreshController,
            enablePullDown: true,
            enablePullUp: false,
            onRefresh: () => {widget.useCache = false, _refresh(context)},
            child: Container(
                    color: ThemeHelper.getPlatformBackgroundColor(context),
                    child: Column(child: ...))

**Comment by nemoryoliver** [comment]
I have this too

**Comment by SebAubin** [comment]
@peng8350 I don't know what else to tell you to give you more details about the bug.

**Comment by peng8350** [comment]
@SebAubin I have tried,It cannot reproduce in normal situation.It need more details.such as 1.reproduce step(describe how to trigger the exception) 2.flutter doctor 3.without any other lib code.Just like [this](https://github.com/peng8350/flutter_pulltorefresh/pull/387)

**Comment by mlandry-devolutions** [comment]
The issue disappear when you add a key to the SmartRefresher. 

`
GlobalKey refresherKey;

  @override
  void initState() {
    super.initState();
    refresherKey = GlobalKey();
  }

SmartRefresher(
            **key: refresherKey,**
            header: sr.ClassicHeader(
              idleText: '',
              refreshingText: '',
              releaseText: '',
            ),
            controller: _refreshController,
            enablePullDown: true,
            enablePullUp: false,
            onRefresh: () => _refresh(),
            child: Container(child: ...));

`

**Comment by peng8350** [comment]
2.0.0 has fixed
