### ISSUE TITLE
进入页面，某些特殊情况会报异常

### ISSUE THREAD

**Issue by s-fei** [peng8350/flutter_pulltorefresh#392]
异常堆栈：
Invalid argument(s): 0.0
#0 _Double.clamp (dart:core-patch/double.dart:184)
#1 BoxConstraints.constrainHeight (package:flutter/src/rendering/box.dart:264)
#2 BoxConstraints.constrain (package:flutter/src/rendering/box.dart:284)
#3 RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:395)
#4 RenderObject.layout (package:flutter/src/rendering/object.dart:1767)
#5 RenderSliverRefreshBody.performLayout (package:pull_to_refresh/src/internals/slivers.dart:545)

异常分析：
internals/slivers中
if (childExtent == 11111) {
      child.layout(
          constraints.asBoxConstraints(
              maxExtent: constraints.viewportMainAxisExtent - 0.1),
          parentUsesSize: true);
}
某些特殊情况viewportMainAxisExtent = 0 会造成height.clamp(minHeight, maxHeight)中的maxHeight为-0.1 小于minHeight 导致flutter异常 麻烦作者尽快修复
顺便问下大神，为什么要减0.1呢😄

**Comment by peng8350** [comment]
那重现代码呢? -0.1是为了让它不满一个屏幕

**Comment by peng8350** [comment]
2.0.0应该修复了,改变成提高而不是减0.1
