### ISSUE TITLE
 A ScrollPositionWithSingleContext was used after being disposed

### ISSUE THREAD

**Issue by sahmadreza** [peng8350/flutter_pulltorefresh#446]
Hi, 

This error occurs when the application is running

There is no problem in executing the list and everything works fine and only this error is displayed in the log console.

`E/flutter (14610): #7      RefreshController.requestRefresh.<anonymous closure>.<anonymous closure> (package:pull_to_refresh/src/smart_refresher.dart:665:17)`
```
E/flutter (14610): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: A ScrollPositionWithSingleContext was used after being disposed.
E/flutter (14610): Once you have called dispose() on a ScrollPositionWithSingleContext, it can no longer be used.
E/flutter (14610): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
E/flutter (14610): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
E/flutter (14610): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
E/flutter (14610): #3      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:889:11)
E/flutter (14610): #4      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:367:5)
E/flutter (14610): #5      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:202:7)
E/flutter (14610): #6      ScrollPositionWithSingleContext.animateTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:181:7)
**E/flutter (14610): #7      RefreshController.requestRefresh.<anonymous closure>.<anonymous closure> (package:pull_to_refresh/src/smart_refresher.dart:665:17)**
E/flutter (14610): #8      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (14610): #9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14610): #10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (14610): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (14610): #12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (14610): #13     Future._complete (dart:async/future_impl.dart:519:7)
E/flutter (14610): #14     new Future.delayed.<anonymous closure> (dart:async/future.dart:323:16)
E/flutter (14610): #15     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (14610): #16     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14610): #17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14610): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (14610): #19     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (14610): #20     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14610): #21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (14610): #22     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (14610): #23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (14610): #24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (14610): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
Application pattern : 
```
- App
-- BlocBuilder
  --- MaterialApp
    ---- CalendarScreen (Scaffold->SafeArea->TabBarView)
     ----- SmartRefresher
      ------ ListView.builder
```

- pull_to_refresh version 1.6.3
- Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
- Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
- Engine • revision 2f0af37152
- Tools • Dart 2.10.5
- Android Studio 4.1.1
- Tested on android device (Android 8.0.0) (Samsung C9 pro)
- Windows 10

**Comment by sobriver** [comment]
me too

**Comment by peng8350** [comment]
example code?

**Comment by topjx** [comment]
+1

**Comment by CaramelFur** [comment]
I too have this issue, has anyone got a fix?

**Comment by mrqaidi** [comment]
up

**Comment by Liberations** [comment]
一样啊 还没修复吗。。
