### ISSUE TITLE
null safety版本，下拉时报异常

### ISSUE THREAD

**Issue by Leadrive** [peng8350/flutter_pulltorefresh#464]
````log
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for ValueNotifier<RefreshStatus>:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3864:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3878:6)
#2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3926:12)
#3      SmartRefresher.ofState (package:pull_to_refresh/src/smart_refresher.dart:275:20)
#4      RefreshIndicatorState._handleModeChange (package:pull_to_refresh/src/internals/indicator_wrap.dart:244:24)
````

Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.17763.1697], locale zh-CN)
    • Flutter version 2.0.3 at C:\flutter
    • Framework revision 4d7946a68d (4 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by peng8350** [comment]
I think this is same with #316

**Comment by peng8350** [comment]
2.0.0已经修复
