### ISSUE TITLE
BezierCircleHeader crashes with `v2.0.0` (working with `v1.6.4`)

### ISSUE THREAD

**Issue by reeteshranjan** [peng8350/flutter_pulltorefresh#490]
I have been using BezierCircleHeader using `1.6.4` successfully. Recently, I migrated to null safety and looked to use `2.0.0`, and it crashes.

### Flutter environment

```bash
$ flutter --version
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (10 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

### Working code that started failing

```dart
SmartRefresher pullRefresh({
  Key? key,
  required RefreshController refreshController,
  required VoidCallback onRefresh,
  VoidCallback? onLoading,
  required Widget child,
}) {
  return SmartRefresher(
    key: key,
    enablePullDown: true,
    enablePullUp: false,
    header: BezierCircleHeader(
      bezierColor: GetIt.I<ThemeProfile>().themeColor.accentSecondary,
      rectHeight: GetIt.I<ThemeProfile>().refresherDimension.bezierRectSize,
      dismissType: BezierDismissType.None,
      circleType: BezierCircleType.Progress,
      circleRadius:
          GetIt.I<ThemeProfile>().refresherDimension.bezierCircleRadius,
    ),
    controller: refreshController,
    onRefresh: onRefresh,
    onLoading: onLoading,
    child: child,
  );
}
```

**Note**: The code has been migrated to null-safety; however, the state machine of the application that uses this code is the same and `refreshController` is a valid initialised controller.

### Exception

This is part of the exception stack trace:

```bash
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building BezierCircleHeader(dirty, dependencies:
[_EffectiveTickerMode], state: _BezierCircleHeaderState#2d0c7(tickers: tracking 3 tickers)):
type 'AlignmentGeometryTween' is not a subtype of type 'Animatable<AlignmentGeometry>' in type cast

The relevant error-causing widget was:
  BezierCircleHeader
  file:///Users/reeteshranjan/src/flutter/app_framework/lib/widgets/refresh.dart:20:13

When the exception was thrown, this was the stack:
#0      _BezierCircleHeaderState.build (package:pull_to_refresh/src/indicator/bezier_indicator.dart:428:38)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4737:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#9      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
#10     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:32)
#11     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:222:11)
...     Normal element mounting (59 frames)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
#72     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:136:18)
#73     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
#74     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:118:12)
#75     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1889:59)
#76     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:912:15)
#77     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1889:14)
#78     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225:7)
#79     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:360:5)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#81     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#83     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
#84     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#85     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#95     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
#96     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#97     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#109    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3368:14)
#110    RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#112    RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#113    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
#114    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636:7)
#115    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
#116    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
#117    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#118    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#119    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#120    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#121    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#125    _invoke (dart:ui/hooks.dart:163:10)
#126    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#127    _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type
RenderErrorBox.

Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type
RenderErrorBox.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4269 pos 14:
'owner!._debugCurrentBuildTarget == this': is not true.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4269 pos 14:
'owner!._debugCurrentBuildTarget == this': is not true.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4269 pos 14:
'owner!._debugCurrentBuildTarget == this': is not true.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4269 pos 14:
'owner!._debugCurrentBuildTarget == this': is not true.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4269 pos 14:
'owner!._debugCurrentBuildTarget == this': is not true.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4269 pos 14:
'owner!._debugCurrentBuildTarget == this': is not true.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2539 pos 20:
'_debugCurrentBuildTarget == context': is not true.

Another exception was thrown: RenderBox was not laid out: _RenderLayoutBuilder#db3e5 relayoutBoundary=up2 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderPadding#d96f3 relayoutBoundary=up1 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderStack#3b893 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#e901e NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#bbb36 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#32934 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#8bb1f NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderStack#32e51 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#60050 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#e0311 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#d15a5 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#eb29f NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#6b0ed NEEDS-PAINT

Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#eb29f NEEDS-PAINT

Another exception was thrown: Updated layout information required for RenderErrorBox#f617b NEEDS-LAYOUT NEEDS-PAINT to
calculate semantics.
```

### Workarounds

The exception is not seen if I use `WaterDropHeader` in place of `BezierCircleHeader`.

I love the UX of `BezierCircleHeader`, so hoping it can be fixed asap for me to retain it.

**Comment by XExistence** [comment]
Did you manage to see what might be causing this issue, maybe we can tag team and create a PR for it coz I really love the UI as well and cant compromise on it. @reeteshranjan

**Comment by reeteshranjan** [comment]
> Did you manage to see what might be causing this issue, maybe we can tag team and create a PR for it coz I really love the UI as well and cant compromise on it. @reeteshranjan

I did not have time to look into code. As of now I have changed my code to use flutter_easyrefresh. It also has a Bezier circle wait/load animation, and it works.

**Comment by XExistence** [comment]
> > Did you manage to see what might be causing this issue, maybe we can tag team and create a PR for it coz I really love the UI as well and cant compromise on it. @reeteshranjan
> 
> 
> 
> I did not have time to look into code. As of now I have changed my code to use flutter_easyrefresh. It also has a Bezier circle wait/load animation, and it works.

Alright, I opted for custom header that fits better with all in app indicators. Feels more coherent now.

**Comment by Spiderbezno** [comment]
I have the same error, any solution??

**Comment by XExistence** [comment]
> I have the same error, any solution??

CustomHeader, that's my current workaround until it's fixed

**Comment by fanpener** [comment]
的确是用不了了 等待修复

**Comment by 826327700** [comment]
我也想用BezierCircleHeader，只能等作者修复了，先用easyrefresh等着

**Comment by zrone** [comment]
> pub.dev/pull_to_refresh_flutter3-2.0.2/lib/src/indicator/bezier_indicator.dart
```
line 301: late Tween<AlignmentGeometry?> _childMoveTween; 
->        late Tween<AlignmentGeometry> _childMoveTween; 

line 312: _childMoveTween = AlignmentGeometryTween(begin: Alignment.bottomCenter, end: Alignment.center);
->        _childMoveTween = Tween<AlignmentGeometry>(begin: Alignment.bottomCenter, end: Alignment.center);
```
