### ISSUE TITLE
This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built

### ISSUE THREAD

**Issue by topjx** [peng8350/flutter_pulltorefresh#507]
The following assertion was thrown while dispatching notifications for ValueNotifier<bool>:
Build scheduled during frame.

While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

**Comment by Jinxishihenian** [comment]
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for ValueNotifier<bool>:
Build scheduled during frame.

While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

When the exception was thrown, this was the stack: 
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:781:9)
#1      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2605:24)
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4879:12)
#3      State.setState (package:flutter/src/widgets/framework.dart:1158:15)
#4      LoadIndicatorState.enterLoading (package:pull_to_refresh/src/internals/indicator_wrap.dart:364:5)
#5      LoadIndicatorState._listenScrollEnd (package:pull_to_refresh/src/internals/indicator_wrap.dart:507:51)
#6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:530:5)
#8      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:987:25)
#9      ScrollPositionWithSingleContext.beginActivity (package:flu

The same error, I noticed that this error came from the enterLoading method in the indicator_wrap.dart file, which called the setState method, I think because of this problem, the setSate was called during build.
