### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by LinHuanTanLy** [peng8350/flutter_pulltorefresh#524]
`1
#0 ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:196)
2
#1 IndicatorStateMixin.disposeListener (package:pull_to_refresh/src/internals/indicator_wrap.dart:614)
3
#2 IndicatorStateMixin.dispose (package:pull_to_refresh/src/internals/indicator_wrap.dart:655)
4
#3 StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4800)
5
#4 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1847)
6
#5 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
7
#6 MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6185)
8
#7 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
9
#8 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
10
#9 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
11
#10 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
12
#11 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
13
#12 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
14
#13 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
15
#14 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
16
#15 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
17
#16 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
18
#17 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
19
#18 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
20
#19 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
21
#20 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
22
#21 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
23
#22 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
24
#23 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
25
#24 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
26
#25 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
27
#26 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
28
#27 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
29
#28 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
30
#29 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
31
#30 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
32
#31 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
33
#32 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
34
#33 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
35
#34 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
36
#35 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
37
#36 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
38
#37 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
39
#38 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
40
#39 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
41
#40 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
42
#41 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
43
#42 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
44
#43 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
45
#44 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
46
#45 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
47
#46 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
48
#47 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
49
#48 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
50
#49 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
51
#50 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
52
#51 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
53
#52 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
54
#53 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
55
#54 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
56
#55 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
57
#56 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
58
#57 _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:71)
59
#58 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
60
#59 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
61
#60 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
62
#61 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
63
#62 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
64
#63 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
65
#64 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
66
#65 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
67
#66 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
68
#67 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
69
#68 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
70
#69 MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6185)
71
#70 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
72
#71 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
73
#72 MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6185)
74
#73 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
75
#74 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
76
#75 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
77
#76 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
78
#77 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
79
#78 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
80
#79 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
81
#80 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
82
#81 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
83
#82 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
84
#83 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
85
#84 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
86
#85 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
87
#86 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
88
#87 MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6185)
89
#88 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
90
#89 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
91
#90 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
92
#91 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
93
#92 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
94
#93 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
95
#94 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
96
#95 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
97
#96 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
98
#97 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
99
#98 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
100
#99 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
101
#100 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
102
#101 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
103
#102 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
104
#103 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
105
#104 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
106
#105 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
107
#106 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
108
#107 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
109
#108 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
110
#109 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
111
#110 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
112
#111 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
113
#112 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
114
#113 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
115
#114 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
116
#115 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
117
#116 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
118
#117 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
119
#118 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
120
#119 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
121
#120 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
122
#121 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
123
#122 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
124
#123 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
125
#124 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
126
#125 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
127
#126 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
128
#127 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
129
#128 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
130
#129 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
131
#130 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
132
#131 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
133
#132 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
134
#133 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
135
#134 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
136
#135 MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6185)
137
#136 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
138
#137 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
139
#138 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
140
#139 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
141
#140 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
142
#141 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
143
#142 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
144
#143 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
145
#144 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
146
#145 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
147
#146 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
148
#147 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
149
#148 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
150
#149 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
151
#150 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
152
#151 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
153
#152 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
154
#153 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
155
#154 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
156
#155 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
157
#156 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
158
#157 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
159
#158 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
160
#159 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
161
#160 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
162
#161 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
163
#162 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
164
#163 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
165
#164 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
166
#165 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
167
#166 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
168
#167 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
169
#168 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
170
#169 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
171
#170 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
172
#171 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
173
#172 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
174
#173 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
175
#174 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
176
#175 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
177
#176 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
178
#177 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
179
#178 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
180
#179 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
181
#180 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
182
#181 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
183
#182 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
184
#183 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
185
#184 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
186
#185 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
187
#186 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
188
#187 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
189
#188 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
190
#189 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
191
#190 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
192
#191 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
193
#192 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
194
#193 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
195
#194 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
196
#195 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
197
#196 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
198
#197 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
199
#198 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
200
#199 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
201
#200 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
202
#201 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
203
#202 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
204
#203 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
205
#204 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
206
#205 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
207
#206 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
208
#207 ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628)
209
#208 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
210
#209 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
211
#210 _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:268)
212
#211 _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843)
213
#212 _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845)
214
#213 ComponentEle...too long be cutted!`

**Comment by MsXam** [comment]
https://github.com/peng8350/flutter_pulltorefresh/issues/529#issuecomment-908344706
