### ISSUE TITLE
After upgrade Flutter to 2.5.0 plugin throws exception

### ISSUE THREAD

**Issue by PcolBP** [peng8350/flutter_pulltorefresh#535]
After upgrading flutter to 2.5.0 library throws exceptions as below, removing SmartRefresher from widget tree resolves problem.

Problem not occur in version of Flutter 2.2.3

| Variable Name  | Value |
| ------------- | ------------- |
|  primary  | false |
| enablePullUp | true |

<details>
<summary>Exceptions:</summary>

```
I/flutter (21834): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (21834): The following assertion was thrown while notifying status listeners for AnimationController:
I/flutter (21834): The Scrollbar's ScrollController has no ScrollPosition attached.
I/flutter (21834): A Scrollbar cannot be painted without a ScrollPosition.
I/flutter (21834): The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be
I/flutter (21834): associated with the ScrollView that the Scrollbar is being applied to. A ScrollView with an
I/flutter (21834): Axis.vertical ScrollDirection will automatically use the PrimaryScrollController if the user has not
I/flutter (21834): provided a ScrollController, but a ScrollDirection of Axis.horizontal will not. To use the
I/flutter (21834): PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.
I/flutter (21834): 
I/flutter (21834): When the exception was thrown, this was the stack:
I/flutter (21834): #0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1285:9)
I/flutter (21834): #1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1310:6)
I/flutter (21834): #2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1257:14)
I/flutter (21834): #3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)
I/flutter (21834): #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:814:7)
I/flutter (21834): #5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:748:5)
I/flutter (21834): #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:611:12)
I/flutter (21834): #7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:462:12)
I/flutter (21834): #8      RawScrollbarState._handleScrollNotification (package:flutter/src/widgets/scrollbar.dart:1567:37)
I/flutter (21834): #9      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:206:42)
I/flutter (21834): #10     Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:122:20)
I/flutter (21834): #11     ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
I/flutter (21834): #12     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4133:39)
I/flutter (21834): #13     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:138:13)
I/flutter (21834): #14     DragScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:465:139)
I/flutter (21834): #15     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:899:15)
I/flutter (21834): #16     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:279:9)
I/flutter (21834): #17     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
I/flutter (21834): #18     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:124:5)
I/flutter (21834): #19     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
I/flutter (21834): #20     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:647:12)
I/flutter (21834): #21     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:449:55)
I/flutter (21834): #22     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
I/flutter (21834): #23     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:449:7)
I/flutter (21834): #24     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:298:9)
I/flutter (21834): #25     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
I/flutter (21834): #26     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
I/flutter (21834): #27     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
I/flutter (21834): #28     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
I/flutter (21834): #29     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
I/flutter (21834): #30     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
I/flutter (21834): #31     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
I/flutter (21834): #32     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
I/flutter (21834): #33     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
I/flutter (21834): #34     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
I/flutter (21834): #35     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
I/flutter (21834): #36     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
I/flutter (21834): #40     _invoke1 (dart:ui/hooks.dart:185:10)
I/flutter (21834): #41     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
I/flutter (21834): #42     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
I/flutter (21834): (elided 3 frames from dart:async)
I/flutter (21834): 
I/flutter (21834): The AnimationController notifying status listeners was:
I/flutter (21834):   AnimationController#07e1e(▶ 0.000)
I/flutter (21834): ════════════════════════════════════════════════════════════════════════════════════════════════════

I/flutter (21834): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (21834): The following assertion was thrown while notifying status listeners for AnimationController:
I/flutter (21834): The Scrollbar's ScrollController has no ScrollPosition attached.
I/flutter (21834): A Scrollbar cannot be painted without a ScrollPosition.
I/flutter (21834): The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be
I/flutter (21834): associated with the ScrollView that the Scrollbar is being applied to. A ScrollView with an
I/flutter (21834): Axis.vertical ScrollDirection will automatically use the PrimaryScrollController if the user has not
I/flutter (21834): provided a ScrollController, but a ScrollDirection of Axis.horizontal will not. To use the
I/flutter (21834): PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.
I/flutter (21834): 
I/flutter (21834): When the exception was thrown, this was the stack:
I/flutter (21834): #0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1285:9)
I/flutter (21834): #1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1310:6)
I/flutter (21834): #2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1257:14)
I/flutter (21834): #3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)
I/flutter (21834): #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:814:7)
I/flutter (21834): #5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:830:5)
I/flutter (21834): #6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
I/flutter (21834): #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
I/flutter (21834): #8      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1056:11)
I/flutter (21834): #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
I/flutter (21834): #10     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1054:17)
I/flutter (21834): #11     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:975:5)
I/flutter (21834): #15     _invoke1 (dart:ui/hooks.dart:185:10)
I/flutter (21834): #16     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
I/flutter (21834): #17     _beginFrame (dart:ui/hooks.dart:116:31)
I/flutter (21834): (elided 3 frames from dart:async)
I/flutter (21834): 
I/flutter (21834): The AnimationController notifying status listeners was:
I/flutter (21834):   AnimationController#07e1e(⏭ 1.000; paused)
I/flutter (21834): ════════════════════════════════════════════════════════════════════════════════════════════════════

I/flutter (21834): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (21834): The following assertion was thrown while notifying status listeners for AnimationController:
I/flutter (21834): The Scrollbar's ScrollController has no ScrollPosition attached.
I/flutter (21834): A Scrollbar cannot be painted without a ScrollPosition.
I/flutter (21834): The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be
I/flutter (21834): associated with the ScrollView that the Scrollbar is being applied to. A ScrollView with an
I/flutter (21834): Axis.vertical ScrollDirection will automatically use the PrimaryScrollController if the user has not
I/flutter (21834): provided a ScrollController, but a ScrollDirection of Axis.horizontal will not. To use the
I/flutter (21834): PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.
I/flutter (21834): 
I/flutter (21834): When the exception was thrown, this was the stack:
I/flutter (21834): #0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1285:9)
I/flutter (21834): #1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1310:6)
I/flutter (21834): #2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1257:14)
I/flutter (21834): #3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)
I/flutter (21834): #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:814:7)
I/flutter (21834): #5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:748:5)
I/flutter (21834): #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:611:12)
I/flutter (21834): #7      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:495:12)
I/flutter (21834): #8      RawScrollbarState._maybeStartFadeoutTimer.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1412:37)
I/flutter (21834): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (21834): 
I/flutter (21834): The AnimationController notifying status listeners was:
I/flutter (21834):   AnimationController#07e1e(◀ 1.000)
I/flutter (21834): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>

My configuration:

```
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1202], locale pl-PL)
    • Flutter version 2.5.0 at C:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\SDK
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.1)
    • VS Code at C:\Users\Pioter\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • SM G965F (mobile) • 22c23a7c140d7ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 93.0.961.44

• No issues found!
```

**Comment by PcolBP** [comment]
Related to [this](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) I think. Migration of plugins to the new behavior of scroll has to be done.

**Comment by PcolBP** [comment]
Fixed. In my case in ScrollBehaviour in buildScrollbar was missing controller

Code before: 

```
@override
  Widget buildScrollbar(
    BuildContext context,
    Widget child,
    ScrollableDetails details,
  ) {
    return CupertinoScrollbar(
      scrollbarOrientation: ScrollbarOrientation.right,
      thicknessWhileDragging: 10,
      thickness: thickness,
      radius: const Radius.circular(5),
      child: child,
    );
}
```

Code after:

```
@override
  Widget buildScrollbar(
    BuildContext context,
    Widget child,
    ScrollableDetails details,
  ) {
    return CupertinoScrollbar(
      controller: details.controller, // change is here, scrollbar was missing controller, in previous version of flutter was inherited by default I think
      scrollbarOrientation: ScrollbarOrientation.right,
      thicknessWhileDragging: 10,
      thickness: thickness,
      radius: const Radius.circular(5),
      child: child,
    );
  }
```

I'll left it open for some time for others to notice.
